spring:
    application:
        name: datapulse
    datasource:
        url: jdbc:mysql://localhost:3306/datapulse?createDatabaseIfNotExist=true
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 
    jpa:
        show-sql: true
        database: mysql
        hibernate:
            ddl-auto: update
        
    server:
        port: 8082
